/**
 * Created by Stanso on 3/8/2015.
 */
public enum Activity {
    ASSIGN_PATIENT_A_CLICKED,
    ASSIGN_PATIENT_B_CLICKED,
    ASSIGN_DOCTOR_CLICKED,
    ASSIGN_NURSE_CLICKED,
    ASSIGN_SURGEON_CLICKED,
    REQUEST_DOCTOR_CLICKED,
    REQUEST_NURSE_CLICKED,
    REQUEST_SURGEON_CLICKED,
    PRE_GIVE_CLICKED,
    GIVE_DOCTOR_CLICKED,
    GIVE_NURSE_CLICKED,
    GIVE_SURGEON_CLICKED,
    ROOM_CLICKED,
    NOTHING_CLICKED
}